
services:
  app:
    build: ./app/src
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - SERVICE_FQDN_APP_80
    volumes:
      - ./app/src:/app
  redis:
    image: redis:latest
    restart: unless-stopped
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${SERVICE_PASSWORD_MYSQLROOT}
      - MARIADB_DATABASE=arkservertools
      - MARIADB_USER=${SERVICE_USER_MYSQL}
      - MARIADB_PASSWORD=${SERVICE_PASSWORD_MYSQL}
    volumes:
      - arkservertools_database:/var/lib/mysql